spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    slow-sql:true
server:
    context-path:/sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  file: /Users/chencheng/logs/sell.log
#  level: debug
